apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: infra-server-service
  namespace: reddwarf-pro
  labels:
    app: infra-server-service
spec:
  replicas: 1
  revisionHistoryLimit: 10
  serviceName: infra-server-service
  podManagementPolicy: OrderedReady
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  selector:
    matchLabels:
      app: infra-server-service
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: infra-server-service
    spec:
      containers:
        - name: infra-server-service
          image: registry.cn-hongkong.aliyuncs.com/reddwarf-pro/infra-server:f676a46be768a69ef3d95b67e3b1656aa5f5e530
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: TEXHUB_REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: infra-server-service-pro-config
                  key: texhub_redis_addr
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: infra-server-service-pro-config
                  key: redis_addr
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: infra-server-service-pro-config
                  key: jwt_secret
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: infra-server-service-pro-config
                  key: database_url
            - name: SELLER_ID
              valueFrom:
                configMapKeyRef:
                  name: infra-server-service-pro-config
                  key: seller_id
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: infra-server-service-pro-config
                  key: env
            - name: IGNORE_LOGIN_URL
              valueFrom:
                configMapKeyRef:
                  name: infra-server-service-pro-config
                  key: ignore_login_url
            - name: SMS_TEST_PHONE
              valueFrom:
                configMapKeyRef:
                  name: infra-server-service-pro-config
                  key: sms_test_phone
            - name: LIMIT_PER_DAY
              valueFrom:
                configMapKeyRef:
                  name: infra-server-service-pro-config
                  key: limit_per_day
            - name: CF_TURNSTILE_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: infra-server-service-pro-config
                  key: cf_turnstile_secret_key
          resources:
            limits:
              cpu: 100m
              memory: 60Mi
            requests:
              cpu: 20m
              memory: 15Mi
          livenessProbe:
            httpGet:
              path: /infra/actuator/liveness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: hongkong-regcred
      schedulerName: default-scheduler
