apiVersion: v1
kind: Service
metadata:
  name: infra-server-service
  namespace: reddwarf-pro
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: infra-server-service
  clusterIP: 10.100.155.34
  clusterIPs:
    - 10.100.155.34
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
