apiVersion: v1
kind: Service
metadata:
  name: infra-server-service
  namespace: reddwarf-pro
  labels:
    app: infra-server-service
spec:
  type: ClusterIP
  selector:
    app: infra-server-service
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
