apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-server-service
  namespace: reddwarf-pro
spec:
  replicas: 0
  selector:
    matchLabels:
      app: infra-server-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: infra-server-service
      annotations:
        kubectl.kubernetes.io/restartedAt: '2024-06-15T08:59:08Z'
        telepresence.getambassador.io/restartedAt: '2024-07-06T15:05:16Z'
    spec:
      containers:
        - name: infra-server-service
          image: >-
            registry.cn-hongkong.aliyuncs.com/reddwarf-pro/infra-server:bc95cc4c704927a47a11caccdeed9467a2e32104
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: TEXHUB_REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: infra-server-service-pro-config
                  key: texhub_redis_addr
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: infra-server-service-pro-config
                  key: redis_addr
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: infra-server-service-pro-config
                  key: jwt_secret
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: infra-server-service-pro-config
                  key: database_url
            - name: SELLER_ID
              valueFrom:
                configMapKeyRef:
                  name: infra-server-service-pro-config
                  key: seller_id
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: infra-server-service-pro-config
                  key: env
          resources:
            limits:
              cpu: 100m
              memory: 60Mi
            requests:
              cpu: 20m
              memory: 15Mi
          livenessProbe:
            httpGet:
              path: /infra/actuator/liveness
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: hongkong-regcred
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
